# Generated by Django 2.0.5 on 2018-09-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_auto_20180918_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='foodie.Preference'),
        ),
    ]
